toDay
eunjin0212/salfJavaScript pull request #1
Opened 2020-09-22 10:40 UTC by eunjin0212

오늘 한 것 -어쩌고 저쩌고

2020-09-22 10:40 UTC, eunjin0212 commented
@changhoi

2020-09-23 11:28 UTC, changhoi requested changes
conflict를 제대로 해결하지 못해서 코드에 문제가 발생할 것임

2020-09-23 11:28 UTC, changhoi commented on momentum/todo.js
> +  toDoInput = todoform.querySelector(".todo-input");
이거 뭔디 코드에 남아있는건지?

2020-09-23 11:28 UTC, changhoi commented on momentum/todo.js
> +  };
```js
const todoObj = {
	text,
	id: newTodo
}
```

객체에서 key 이름과 value 변수의 이름이 같으면 `{key: value}` 형태로 작성할 필요 없이 `{ key }`로 작성할 수 있음

2020-09-23 11:28 UTC, changhoi commented on momentum/todo.js
> +  }
이렇게 작성하면 무조건 `true` 값이 될텐데? 예를 들어서
```js
const userTodoList = [];
const todoObj = {
	text,
	id: newTodo
}

const listLength = userTodoList.push(todoObj);
console.log(listLength); // 1
```

1값이 리턴되니까, 무조건 if 문은 true가 됨 로직상 문제가 있을 것 같음

2020-09-23 11:28 UTC, changhoi commented on momentum/todo.js
> +>>>>>>> 2dcd82f38ba5364f4fde6baec9029135b092e488
이것도 코드에 남아있으면, 제대로 동작 하지 않을 것

2020-09-23 11:56 UTC, merged